server:
  port: 8888
  servlet:
    contextPath: /config

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aknon/cloudconfig.git
  application:
    name: configserver
#security:
#  user:
#    name: nitesh
#    password: nitesh

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics







